spring:
  application:
    name: scm-platform
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.scm.domain
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

