server:
  port: 8080
  session:
    timeout: 1200
spring:
  application:
    name: scm-platform
  profiles:
    active: dev
  http:
      converters:
        preferred-json-mapper: fastjson
      multipart:
        max-request-size: 100MB #最大请求大小
        max-file-size: 100MB #最大文件大小

  aop:
      proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    view:
      prefix: /template
  datasource:
    url: jdbc:mysql://localhost:3306/scm?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.scm.platform.entity
  global-config:
    id-type: 0
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

